# Generated by Django 4.2.6 on 2023-10-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_author_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
