# Generated by Django 4.2.6 on 2023-10-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_book_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='released_at',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='user_add_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
