# Generated by Django 4.2.6 on 2023-10-09 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_rename_author_id_book_author_alter_book_released_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user_add_id',
        ),
        migrations.AddField(
            model_name='book',
            name='user_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
