# Generated by Django 4.2.6 on 2023-10-10 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0009_author_user_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_add_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.book'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
